// Alternate names players plausibly type instead of the dataset's own name:
// official long forms ("Kingdom of Saudi Arabia"), former names ("Burma"),
// abbreviations ("UAE"), and a few endonyms that turn up in general knowledge
// ("Deutschland"). Punctuation, diacritics, spacing and a leading "the" are
// all handled by the normaliser in countryMatch.ts, so there's no need for a
// variant that only differs in those — "Cote d'Ivoire" covers "cote d ivoire".
//
// Keys must match `name` in countries.json exactly. countries.json is
// regenerated rather than hand-edited, so a rename upstream would orphan a
// key here; countryMatch.ts warns about orphans in dev.
export const COUNTRY_ALIASES: Record<string, readonly string[]> = {
  Austria: ["Österreich"],
  Bahamas: ["The Bahamas", "Commonwealth of the Bahamas"],
  Belarus: ["Byelorussia", "Belorussia", "White Russia"],
  Belgium: ["Belgique", "België"],
  Benin: ["Dahomey"],
  Bolivia: ["Plurinational State of Bolivia"],
  "Bosnia and Herzegovina": ["Bosnia", "Bosnia-Herzegovina", "Herzegovina", "BiH"],
  Brazil: ["Brasil"],
  Brunei: ["Brunei Darussalam"],
  "Burkina Faso": ["Upper Volta"],
  "Cabo Verde": ["Cape Verde"],
  Cambodia: ["Kampuchea", "Khmer Republic"],
  "Central African Republic": ["CAR", "Centrafrique"],
  China: ["People's Republic of China", "PRC", "Mainland China"],
  Congo: ["Republic of the Congo", "Congo-Brazzaville", "Congo Republic"],
  "Côte d'Ivoire": ["Ivory Coast", "Ivorian Republic"],
  Croatia: ["Hrvatska"],
  Czechia: ["Czech Republic"],
  Denmark: ["Danmark"],
  "DR Congo": [
    "Democratic Republic of the Congo",
    "Democratic Republic of Congo",
    "DRC",
    "Congo-Kinshasa",
    "Zaire",
  ],
  Egypt: ["Arab Republic of Egypt", "Misr"],
  Eswatini: ["Swaziland"],
  Ethiopia: ["Abyssinia"],
  Finland: ["Suomi"],
  Gambia: ["The Gambia"],
  Georgia: ["Sakartvelo"],
  Germany: ["Deutschland", "Federal Republic of Germany", "West Germany"],
  Greece: ["Hellas", "Hellenic Republic"],
  Guinea: ["Guinea-Conakry", "Republic of Guinea"],
  Hungary: ["Magyarország"],
  India: ["Bharat", "Hindustan"],
  Iran: ["Persia", "Islamic Republic of Iran"],
  Ireland: ["Republic of Ireland", "ROI", "Éire"],
  Italy: ["Italia"],
  Japan: ["Nippon", "Nihon"],
  Kazakhstan: ["Republic of Kazakhstan"],
  Kyrgyzstan: ["Kyrgyz Republic", "Kirghizia"],
  Laos: ["Lao PDR", "Lao People's Democratic Republic"],
  Libya: ["State of Libya"],
  Micronesia: ["Federated States of Micronesia", "FSM"],
  Moldova: ["Republic of Moldova"],
  Morocco: ["Maroc", "Kingdom of Morocco"],
  Myanmar: ["Burma"],
  Netherlands: ["Holland", "Nederland"],
  "New Zealand": ["Aotearoa"],
  "North Korea": ["Democratic People's Republic of Korea", "DPRK"],
  "North Macedonia": ["Macedonia", "FYROM", "Former Yugoslav Republic of Macedonia"],
  Norway: ["Norge"],
  "Papua New Guinea": ["PNG"],
  Poland: ["Polska"],
  Russia: ["Russian Federation", "Rossiya"],
  "Saint Kitts and Nevis": ["St Kitts and Nevis", "Saint Christopher and Nevis", "St Kitts"],
  "Saint Lucia": ["St Lucia"],
  "Saint Vincent and the Grenadines": ["St Vincent and the Grenadines", "St Vincent"],
  "São Tomé and Príncipe": ["Sao Tome"],
  "Saudi Arabia": ["Kingdom of Saudi Arabia", "KSA"],
  Slovakia: ["Slovak Republic"],
  "South Africa": ["Republic of South Africa", "RSA"],
  "South Korea": ["Republic of Korea", "Korea", "ROK"],
  Spain: ["España"],
  "Sri Lanka": ["Ceylon"],
  Sweden: ["Sverige"],
  Switzerland: ["Schweiz", "Suisse", "Helvetia"],
  Syria: ["Syrian Arab Republic"],
  Tanzania: ["United Republic of Tanzania", "Tanganyika"],
  Thailand: ["Siam"],
  "Timor-Leste": ["East Timor"],
  "Trinidad and Tobago": ["Trinidad", "Tobago"],
  Türkiye: ["Turkey"],
  "United Arab Emirates": ["UAE", "Emirates"],
  // The four home nations are here because a player typing "Scotland" means
  // this country — the dataset has no entry of their own for them.
  "United Kingdom": [
    "UK",
    "Great Britain",
    "Britain",
    "United Kingdom of Great Britain and Northern Ireland",
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland",
  ],
  "United States": ["USA", "US", "United States of America", "America"],
  "Vatican City": ["Holy See", "Vatican"],
  Venezuela: ["Bolivarian Republic of Venezuela"],
  Vietnam: ["Viet Nam", "Socialist Republic of Vietnam"],
  Zimbabwe: ["Rhodesia"],
};
